# General settings
project_name: "Anomaly Detection System for Corporate Fleets through Continuous Learning"
random_seed: 42
log_level: "INFO"

# Data settings
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
#  train_split: 0.8  # 80% training, 20% testing
  scaler: "StandardScaler"  # Alternative: MinMaxScaler

# Model settings
autoencoder:
  input_dim: 14  # 4 temporal + 10 per data
  window_size: 20
  encoder_layers: [64, 32, 16, 8]
  bottleneck_dim: 4
  decoder_layers: [8, 16, 32, 64]
  activation: "tanh"
  loss_function: "mse"
  optimizer: "adam"
  learning_rate: 0.001
  batch_size: 32
#  epochs: 50

## Forecasting model (to be combined with Autoencoder)
#forecasting:
#  model_type: "LSTM"  # Alternative: GRU, Transformer
#  hidden_units: 64
#  num_layers: 2
#  dropout: 0.2
#  learning_rate: 0.001

# Streaming settings
streaming:
  enabled: true
  batch_size: 10
  sliding_window: 20
  anomaly_threshold: 0.05  # Threshold for anomaly detection

# Paths for saving models
paths:
  model_save_dir: "models/"
  logs_dir: "logs/"
  results_dir: "results/"

# Evaluation settings
evaluation:
  metrics: ["MSE", "MAE", "R2"]
  threshold_method: "dynamic"
